language: ruby
sudo: required
services:
  - docker
before_install:
  - docker pull exorath/mapservice
  - docker run -p 8080:8080 exorath/mapservice -e PORT=8080 -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_KEY -e BUCKET_NAME
script:
  - docker build -t $REPO .
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$REPO";
    fi
