language: java
jdk:
- oraclejdk8
script: mvn clean package
addons:
  artifacts: true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FG4zS+irSlo+iUaOgf70CfTcyzZ79vyvxYv6TGLJ+8oajst+UB6tNihVX9rYXdXosS9Sn/yYVgqOakcJbiPsjD8s2G1xHPrbwGkNBpeR83wLMYei+tgQ4TGs5nisxenKnQl651YRQqH4ew2hFUZDPAdHDPMKK49sqmi2mhcSJ2y124c1hNG+a4hKCDS9vazW9jmbTMeTtkaMrZtFY/k7bSJ6rhy1XfX83ocRohJAuIAcrckTMMND1HSxkd49SwpTkLNuUvScoE+5r+xBmOdPp/uE/woBsU6OjRJh9xDZotD+rgRrmtKzVkwiMklqt75SZwY0NcR/k61AMlHprNA0AkNKqTQrA4hiaB/pdJZMdW+ioQUkUn7uj6w6XKqHwqFG9fnewcZq1lCV3SdtICAMVHIkUvBx85RlVcoStSqV3Ur683+Nml5OaFvoy2pqpMk9mbiLh3Oay0f1VbthcrJHbW6wDWlv2lS41wvNjMliV7Cb2ngWIYPihZbL6/nW9Qtx7n2se8T+HiN2cDw7NDnoRhqCP8BFRFhRXSiKv9Av6K3zNl4yUZIcGdGX31cVdmon7vthNaGWWv6B7D/xJNKfPEwykPXxo27NNV7OAMghh9qGmNYs15S+Ar00lzTaebBLWLCNPcuVcRrO++pUofV/sYT2JDe5HDNw7wqHLBeyOiY=
  file: target/*.jar
  file_glob: true
  on:
    tags: true