#!/bin/bash
echo "startserver v0.0.21 initiated."

createEULA() {
  if [ ! -f eula.txt  ] ; then
       echo "eula=true" > eula.txt
       echo "updated eula.txt"
  fi
}

# EULA stuff
echo "checking eula..."
if [ $0 == "--eula==TRUE" ] ; then
  echo "ERROR: EULA was not accepted, add the --eula=TRUE argument."
  exit 1
fi
createEULA
echo "EULA accepted."

# Starting server stuff
echo "starting server..."
tmux new -s spigot "su - minecraft -c 'exec java -jar server.jar nogui'"
echo "server is terminated."

