#!/bin/bash
echo "startserver v0.0.1 initiated."

createEULA() {
  if [ ! -f eula.txt  ] ; then
       echo '#EULA created by script\neula=true' > $MC_DIR/eula.txt
  fi
}

# EULA stuff
echo "checking eula..."
if [ $0 == "--eula==TRUE" ] ; then
  echo "ERROR: EULA was not accepted, add the --eula=TRUE argument."
  exit 1
fi
createEULA
echo "EULA accepted."

# Starting server stuff
echo "starting server..."
java -jar server.jar
echo "server is terminated."

