#!/bin/bash
echo "startserver v0.0.24 initiated."

createEULA() {
  if [ ! -f eula.txt  ] ; then
       echo "eula=true" > eula.txt
       echo "updated eula.txt"
  fi
}

# EULA stuff
echo "checking eula..."
if [ $0 == "--eula==TRUE" ] ; then
  echo "ERROR: EULA was not accepted, add the --eula=TRUE argument."
  exit 1
fi
createEULA
echo "EULA accepted."

# Starting server stuff
echo "starting server..."
useradd -s /bin/bash -d $PWD -m minecraft
chmod -R +777 ./
tmux new -s spigot "su -m - minecraft -c 'exec java -jar server.jar nogui'"
echo "server is terminated."

